---
- name: Testing andrewrothstein.opam
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'opam --version'
      ansible.builtin.command: opam --version
      changed_when: false
      register: opam_test_output
    - name: Output from 'opam --version'
      ansible.builtin.debug:
        msg: '{{ opam_test_output.stdout }}'
    - name: Executing 'opam list'
      ansible.builtin.command: opam list
      changed_when: false
      register: opam_list_output
    - name: Output from 'opam list'
      ansible.builtin.debug:
        msg: '{{ opam_list_output.stdout }}'
