---
- name: andrewrothstein.unarchive-deps
  version: v1.2.4
- name: andrewrothstein.bash
  version: v1.1.11
- name: andrewrothstein.alpine-glibc-shim
  version: v2.0.18
- name: andrewrothstein.gcc-toolbox
  version: v1.1.7
- name: andrewrothstein.git
  version: v3.1.7
- name: andrewrothstein.curl
  version: v1.0.15
